---
functional:
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре   #+
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории                       #+
  - Пользователь должен иметь возможность фильтровать товары                                                   #+
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины        #+
  - Пользователь должен иметь возможность корректировать количество товаров в корзине                #+
  - Пользователь должен иметь возможность удалять товары из корзины по одному наименованию                     #+
  - Подбзователь должен иметь возможность очистить корзину полностью одной кнопкой                      #+
  - Пользователь должен иметь возможность оформить заказ добавленных в корзину товаров                  #+
  - После оформления заказа заказанные товары из корзины должны исчезнуть                                #+
non-functional:
  - Пользователь должент иметь возможность переключать язык интерфеса приложения (русский-англиский)    #+  
  - Сайт должен быть безопасным и защищать данные пользователя         #+
  - Сайт должен быть адаптивным к типам устройств для просмотра        #+
  - Сайт должен быть совместим с последними версиями браузеров         #+
  - Сайт должен обеспечивать обработку большого количества трафика (оптимизированная загрузка) #-------------------
  - Во всех блоках (карточках) товаров кнопка "В корзину" одного цвета и размера               #+
  - Приложение должно быть SPA                                                                  #+
  - 
implicit:
...
