---
functional:
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность корректировать количество выбранных товаров в корзине
  - Пользователь должен иметь возможность удалять ьовары из корзины
  - Пользователь должен иметь возможность сделать заказ добавленных в корзину товаров  
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Пользователь должент иметь возможность переключать язык интерфеса приложения (русский-англиский)
implicit:
  - Фото товаров должны быть одного размера и на белом фоне
  - Все фото товаров в едином формате jpg или png
  - Во всех блоках (карточках) товаров кнопка "В корзину" одного цвета и размера
  - Все фото должны быть обработаными и представлены без геометрических искажений
  - Приложение должно быть SPA
